-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.competitii
(
    id_competitie serial NOT NULL,
    nume_competitie character varying(50) COLLATE pg_catalog."default" NOT NULL,
    data_competitie timestamp without time zone NOT NULL,
    id_locatie integer NOT NULL,
    id_sport integer NOT NULL,
    id_manager integer NOT NULL,
    CONSTRAINT competitii_pkey PRIMARY KEY (id_competitie)
);

CREATE TABLE IF NOT EXISTS public.echipe
(
    id_echipa serial NOT NULL,
    nume_echipa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefon_contact character varying(15) COLLATE pg_catalog."default" NOT NULL,
    lot_echipa integer NOT NULL,
    email_echipa character varying(50) COLLATE pg_catalog."default",
    parola_echipa character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT echipe_pkey PRIMARY KEY (id_echipa)
);

CREATE TABLE IF NOT EXISTS public.jucatori
(
    id_jucator serial NOT NULL,
    nume_jucator character varying(50) COLLATE pg_catalog."default" NOT NULL,
    prenume_jucator character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_echipa integer NOT NULL,
    CONSTRAINT jucatori_pkey PRIMARY KEY (id_jucator)
);

CREATE TABLE IF NOT EXISTS public.locatii
(
    id_locatie serial NOT NULL,
    nume_oras character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nume_strada character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nr_strada integer NOT NULL,
    tip_locatie character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT locatii_pkey PRIMARY KEY (id_locatie)
);

CREATE TABLE IF NOT EXISTS public.manageri
(
    id_manager bigserial NOT NULL,
    nume_manager character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prenume_manager character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sex character varying(255) COLLATE pg_catalog."default" DEFAULT 'M'::bpchar,
    email_manager character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parola_manager character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT manageri_pkey PRIMARY KEY (id_manager),
    CONSTRAINT manageri_email_manager_key UNIQUE (email_manager)
);

CREATE TABLE IF NOT EXISTS public.meciuri
(
    id_meci serial NOT NULL,
    nr_locuri integer NOT NULL,
    data_sustinerii timestamp without time zone NOT NULL,
    nume_arbitru character varying(50) COLLATE pg_catalog."default" NOT NULL,
    prenume_arbitru character varying(50) COLLATE pg_catalog."default" NOT NULL,
    id_competitie integer NOT NULL,
    CONSTRAINT meciuri_pkey PRIMARY KEY (id_meci)
);

CREATE TABLE IF NOT EXISTS public.meciurijucatori
(
    id_meci integer NOT NULL,
    id_jucator integer NOT NULL,
    culoare_echipament character varying(20) COLLATE pg_catalog."default" DEFAULT 'Alb'::character varying,
    CONSTRAINT meciurijucatori_pkey PRIMARY KEY (id_meci, id_jucator)
);

CREATE TABLE IF NOT EXISTS public.meciurispectatori
(
    id_meci integer NOT NULL,
    id_spectator integer NOT NULL,
    pret_bilet money NOT NULL,
    CONSTRAINT meciurispectatori_pkey PRIMARY KEY (id_meci, id_spectator)
);

CREATE TABLE IF NOT EXISTS public.spectatori
(
    id_spectator serial NOT NULL,
    nume_spectator character varying(50) COLLATE pg_catalog."default" NOT NULL,
    prenume_spectator character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sex character(1) COLLATE pg_catalog."default" DEFAULT 'M'::bpchar,
    metoda_plata character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email_spectator character varying(50) COLLATE pg_catalog."default" NOT NULL,
    parola_spectator character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT spectatori_pkey PRIMARY KEY (id_spectator)
);

CREATE TABLE IF NOT EXISTS public.sponsori
(
    id_sponsor serial NOT NULL,
    nume_sponsor character varying(50) COLLATE pg_catalog."default" NOT NULL,
    email_sponsor character varying(50) COLLATE pg_catalog."default" NOT NULL,
    telefon_sponsor character varying(15) COLLATE pg_catalog."default" NOT NULL,
    suma_alocata money NOT NULL,
    CONSTRAINT sponsori_pkey PRIMARY KEY (id_sponsor),
    CONSTRAINT sponsori_email_sponsor_key UNIQUE (email_sponsor),
    CONSTRAINT sponsori_telefon_sponsor_key UNIQUE (telefon_sponsor)
);

CREATE TABLE IF NOT EXISTS public.sponsorizari
(
    id_competitie integer NOT NULL,
    id_sponsor integer NOT NULL,
    tip_sponsorizare character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sponsorizari_pkey PRIMARY KEY (id_competitie, id_sponsor)
);

CREATE TABLE IF NOT EXISTS public.sporturi
(
    id_sport serial NOT NULL,
    nume_sport character varying(50) COLLATE pg_catalog."default" NOT NULL,
    este_de_contact boolean NOT NULL,
    durata_joc integer NOT NULL,
    CONSTRAINT sporturi_pkey PRIMARY KEY (id_sport)
);

ALTER TABLE IF EXISTS public.competitii
    ADD CONSTRAINT fk_competitii_locatie FOREIGN KEY (id_locatie)
    REFERENCES public.locatii (id_locatie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.competitii
    ADD CONSTRAINT fk_competitii_manageri FOREIGN KEY (id_manager)
    REFERENCES public.manageri (id_manager) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.competitii
    ADD CONSTRAINT fk_competitii_sporturi FOREIGN KEY (id_sport)
    REFERENCES public.sporturi (id_sport) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.jucatori
    ADD CONSTRAINT fk_jucatori_echipe FOREIGN KEY (id_echipa)
    REFERENCES public.echipe (id_echipa) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.meciuri
    ADD CONSTRAINT fk_meciuri_competitii FOREIGN KEY (id_competitie)
    REFERENCES public.competitii (id_competitie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.meciurijucatori
    ADD CONSTRAINT fk_meciurijucatori_jucatori FOREIGN KEY (id_jucator)
    REFERENCES public.jucatori (id_jucator) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.meciurijucatori
    ADD CONSTRAINT fk_meciurijucatori_meciuri FOREIGN KEY (id_meci)
    REFERENCES public.meciuri (id_meci) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.meciurispectatori
    ADD CONSTRAINT fk_meciurispectatori_meciuri FOREIGN KEY (id_meci)
    REFERENCES public.meciuri (id_meci) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.meciurispectatori
    ADD CONSTRAINT fk_meciurispectatori_spectatori FOREIGN KEY (id_spectator)
    REFERENCES public.spectatori (id_spectator) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sponsorizari
    ADD CONSTRAINT fk_sponsorizari_competitii FOREIGN KEY (id_competitie)
    REFERENCES public.competitii (id_competitie) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sponsorizari
    ADD CONSTRAINT fk_sponsorizari_sponsori FOREIGN KEY (id_sponsor)
    REFERENCES public.sponsori (id_sponsor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
